# Generated by Django 4.2.13 on 2024-06-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_holder',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
